const strings = {
  labels: {
    companyName: 'Dept Work',
    menu: 'menu',
    viewCase: 'view case',
    showMe: 'show me',
    in: 'in',
    name: 'name',
    email: 'email',
    message: 'message',
    send: 'send',
    top: 'top',
    terms: 'Terms and conditions',
    copyright: '© 2018 Dept Agency',
    chamberOfCommerce: 'Chamber of Commerce: 63464101',
    vat: 'VAT: NL 8552.47.502.B01',
  },
  sections: {
    clients: {
      title: 'Clients',
      description:
        'We value a great working relationship with our clients above all else. It’s why they often come to our parties. It’s also why we’re able to challenge and inspire them to reach for the stars.',
    },
    contactUs: { title: 'Questions? We are here top help!' },
  },
  menu: {
    home: 'Home',
    work: 'Work',
    services: 'Services',
    stories: 'Stories',
    about: 'About',
    careers: 'Careers',
    contact: 'Contact',
    events: 'Events',
    werk: 'Werk',
    over: 'Over',
    partners: 'Partners',
    diensten: 'Diensten',
    vacatures: 'Vacatures',
  },
  locations: {
    title: 'landen',
    gl: 'Global',
    nl: 'Nederland',
    us: 'United States',
    ie: 'Ireland',
    uk: 'United Kingdom',
    de: 'Deutschland',
    sw: 'Schweiz',
  },
  socials: {
    fb: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    linkedin: 'LinkedIn',
  },
  errors: {
    invalidEmail: 'Please enter a valid email',
    invalidName: 'Please enter your name',
    invalidMessage: 'Please enter your message',
    errorOnPageLoad: 'Something bad happened. Please try again later.',
  },
};

export default strings;
