export const GET_HOME_LIST_REQUEST = 'GET_HOME_LIST_REQUEST';
export const GET_HOME_LIST_SUCCESS = 'GET_HOME_LIST_SUCCESS';
export const GET_HOME_LIST_START = 'GET_HOME_LIST_START';
export const GET_HOME_LIST_ERROR = 'GET_HOME_LIST_ERROR';

export const REQUEST_HOME_CONTENT = 'REQUEST_HOME_CONTENT';
